name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o gena-darwin cmd/gena/gena.go
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o gena.exe cmd/gena/gena.go
          CGO_ENABLED=0 go build -o gena-linux cmd/gena/gena.go
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            gena-darwin
            gena.exe
            gena-linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
